### PR TITLE
modified build command so that image will push properly

### PR DESCRIPTION
**Pull request by gherlein**
Had to chase this down.  Using original instructions:
docker push gherlein/hello:latest
The push refers to a repository [docker.io/gherlein/hello](len: 1)
Repository does not exist: gherlein/hello

Using changed instructions:
docker build -t gherlein/hello .
Sending build context to Docker daemon 4.389 MB
Step 1 : FROM scratch
 ---> 
Step 2 : ADD hello /
 ---> Using cache
 ---> 5202557bc674
Step 3 : CMD /hello
 ---> Using cache
 ---> 2f1d57e29917
Successfully built 2f1d57e29917

docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
gherlein/hello      latest              2f1d57e29917        19 minutes ago      4.383 MB

docker push gherlein/hello:latest
The push refers to a repository [docker.io/gherlein/hello](len: 1)
2f1d57e29917: Pushed 
5202557bc674: Pushed 
latest: digest: sha256:ac45fd7c1c7f28c880e0504c2fbca9dc4e7fe7f0fd7bd5d84e8fbbd57141f6c4 size: 2744

### CODE REVIEW

**Comment by hazbo** [comment]
Hi there, first of all, thanks for the contribution!

I've gone over this just now to find the best solution. It appears that you may have forgotten to run:

`docker tag IMAGE_ID DOCKERHUB_USERNAME/hello:latest`

before running `docker push`. However, I think we should specify the username / image name in the build command like you have proposed, as this means we'd be able to actually get rid of the `docker tag` command from this process. That may simplify the process for the user.

By default, the `build -t` command will use `latest` for the `TAG`. I think we should keep that there as `:latest` is used further in the tutorial and will make more sense this way.

So here's what I propose, we get rid of all 4 commands and just use what you proposed w/ the tagged version:

```
$ docker build -t DOCKERHUB_USERNAME/hello:latest .
$ docker push DOCKERHUB_USERNAME/hello
```

What do you think about this?

**Comment by gherlein** [comment]
I could have sworn I did the tag, but it's not in my history.  

Yes, I like your way better.  Cleaner and more simple.

**Comment by hazbo** [comment]
Feel free to push those changes to your branch and I'll be able to merge this PR :)

**Comment by gherlein** [comment]
OK, ready

**Pull request merged**
